const qs=new URLSearchParams(location.search);let sid=qs.get('session')||'',token=qs.get('token')||'';
let storedLang=null;try{storedLang=localStorage.getItem('backrow-lang')}catch{}let lang=(qs.get('lang')==='id'||storedLang==='id')?'id':'en',stream=null,lastImage=null,liveRunning=false,liveTimer=null,sendBusy=false,lastProbe=null,lastSentProbe=null,stableHits=0;
const $=s=>document.querySelector(s);
const copy={
 en:{lang:'ID',kicker:'REMOTE AUDIENCE CAPTURE',title:'Stand where the audience sits.',intro:'Keep the entire projected screen inside the frame. Send a capture and the presenter workstation will match it to the source deck automatically.',camera:'OPEN CAMERA',send:'SEND CURRENT FRAME',photo:'TAKE / CHOOSE PHOTO',connecting:'Connecting to presenter session…',ready:'Connected. Capture the projected screen from this position.',sending:'Matching slide and checking what survived…',cameraFail:'Live camera is unavailable here. Use TAKE / CHOOSE PHOTO instead.',sent:'Capture delivered to presenter.',note:'This page does not show the source answer. It only sends the audience-position capture to the paired BACKROW presenter session.',risk:'AT RISK',watch:'WATCH',good:'RECOVERED',slide:'slide',joinKicker:'PAIR WITH PRESENTER',join:'PAIR',joinHelp:'Enter the 6-digit code shown on the presenter workstation.',joining:'Pairing…',liveStart:'START LIVE SCAN',liveStop:'STOP LIVE SCAN',liveActive:'Live scan is running. Leave this phone at the audience position.'},
 id:{lang:'EN',kicker:'TANGKAPAN PENONTON JARAK JAUH',title:'Berdiri di posisi penonton.',intro:'Pastikan seluruh layar proyektor masuk frame. Kirim tangkapan dan workstation presenter akan mencocokkannya ke deck sumber secara otomatis.',camera:'BUKA KAMERA',send:'KIRIM FRAME INI',photo:'AMBIL / PILIH FOTO',connecting:'Menghubungkan ke sesi presenter…',ready:'Terhubung. Ambil layar proyektor dari posisi ini.',sending:'Mencocokkan slide dan mengecek informasi yang bertahan…',cameraFail:'Kamera live tidak tersedia di konteks ini. Pakai AMBIL / PILIH FOTO.',sent:'Tangkapan sudah dikirim ke presenter.',note:'Halaman ini tidak menampilkan jawaban/source. Halaman ini hanya mengirim tangkapan dari posisi penonton ke sesi BACKROW presenter.',risk:'BERISIKO',watch:'PERLU DICEK',good:'TERPULIHKAN',slide:'slide',joinKicker:'HUBUNGKAN KE PRESENTER',join:'HUBUNGKAN',joinHelp:'Masukkan kode 6 digit yang tampil di workstation presenter.',joining:'Menghubungkan…',liveStart:'MULAI SCAN LIVE',liveStop:'STOP SCAN LIVE',liveActive:'Scan live berjalan. Tinggalkan HP ini di posisi penonton.'}
};
function tr(){return copy[lang]}
function renderLang(){const t=tr();$('#langBtn').textContent=t.lang;$('#kicker').textContent=t.kicker;$('#title').textContent=t.title;$('#intro').textContent=t.intro;$('#cameraBtn').textContent=t.camera;$('#sendBtn').textContent=t.send;$('#photoLabel').childNodes[0].nodeValue=t.photo;$('#note').textContent=t.note;$('#joinKicker').textContent=t.joinKicker;$('#joinBtn').textContent=t.join;$('#liveBtn').textContent=liveRunning?t.liveStop:t.liveStart;if(!sid)$('#joinStatus').textContent=t.joinHelp}
function showJoin(){ $('#joinPanel').classList.remove('hidden');$('#capturePanel').classList.add('hidden') }
function showCapture(){ $('#joinPanel').classList.add('hidden');$('#capturePanel').classList.remove('hidden') }
async function pairCode(){const code=$('#joinCode').value.replace(/\D/g,'');if(code.length!==6){$('#joinStatus').textContent=tr().joinHelp;return}$('#joinBtn').disabled=true;$('#joinStatus').textContent=tr().joining;try{const r=await fetch('/api/observer/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({join_code:code})}),j=await r.json();if(!j.ok)throw new Error(j.error||'Pairing failed');sid=j.session_id;token=j.observer_token;try{history.replaceState(null,'',`?session=${encodeURIComponent(sid)}&token=${encodeURIComponent(token)}&lang=${lang}`)}catch{};$('#deckName').textContent=(j.deck_name||'AUDIENCE OBSERVER').toUpperCase();showCapture();$('#status').textContent=tr().ready}catch(e){$('#joinStatus').textContent=e.message}finally{$('#joinBtn').disabled=false}}
async function init(){renderLang();if(!sid||!token){showJoin();return}showCapture();try{const r=await fetch(`/api/observer/${encodeURIComponent(sid)}/public`,{cache:'no-store'}),j=await r.json();if(!j.ok)throw new Error(j.error||'Session unavailable');$('#deckName').textContent=(j.session.deck_name||'AUDIENCE OBSERVER').toUpperCase();$('#status').textContent=tr().ready}catch(e){$('#status').textContent=e.message}}
function showDataUrl(data){lastImage=data;$('#emptyFrame').classList.add('hidden');$('#video').classList.add('hidden');$('#photoPreview').src=data;$('#photoPreview').classList.remove('hidden');$('#sendBtn').classList.remove('hidden')}
async function openCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});$('#emptyFrame').classList.add('hidden');$('#photoPreview').classList.add('hidden');$('#video').srcObject=stream;$('#video').classList.remove('hidden');$('#sendBtn').classList.remove('hidden');$('#liveBtn').classList.remove('hidden');$('#status').textContent=tr().ready}catch(e){$('#status').textContent=tr().cameraFail}}
function currentFrame(){if(lastImage&&$('#photoPreview').classList.contains('hidden')===false)return lastImage;const v=$('#video');if(!stream||!v.videoWidth)return null;const c=$('#canvas'),max=1600,s=Math.min(1,max/v.videoWidth);c.width=Math.round(v.videoWidth*s);c.height=Math.round(v.videoHeight*s);c.getContext('2d').drawImage(v,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.84)}
async function send(quiet=false){if(sendBusy)return false;const image=currentFrame();if(!image){$('#status').textContent=tr().cameraFail;return false}sendBusy=true;$('#sendBtn').disabled=true;if(!quiet)$('#status').textContent=tr().sending;try{const r=await fetch('/api/observer/frame',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid,observer_token:token,view:image})}),j=await r.json();if(!j.ok)throw new Error(j.error||'Capture failed');const c=j.result.counts||{},idx=(j.result.matched_slide_index??0)+1,total=(c.at_risk||0)+(c.watch||0)+(c.supported||0);const worst=(c.at_risk||0)>0?'risk':((c.watch||0)>0?'watch':'good'),label=worst==='risk'?tr().risk:(worst==='watch'?tr().watch:tr().good);$('#result').className=`observerResult ${worst}`;$('#result').classList.remove('hidden');$('#resultTitle').textContent=`${label} · ${tr().slide} ${idx}`;$('#resultMeta').textContent=`${c.at_risk||0} risk · ${c.watch||0} watch · ${c.supported||0} recovered · ${total} regions`;$('#status').textContent=tr().sent;lastImage=null;return true}catch(e){$('#status').textContent=e.message;return false}finally{sendBusy=false;$('#sendBtn').disabled=false}}

function probeFrame(){const v=$('#video');if(!stream||!v.videoWidth)return null;const c=document.createElement('canvas');c.width=32;c.height=24;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data,a=new Uint8Array(c.width*c.height);for(let i=0,j=0;i<d.length;i+=4,j++)a[j]=(d[i]*3+d[i+1]*6+d[i+2])/10;return a}
function probeDelta(a,b){if(!a||!b||a.length!==b.length)return 999;let sum=0;for(let i=0;i<a.length;i++)sum+=Math.abs(a[i]-b[i]);return sum/a.length}
async function liveTick(){if(!liveRunning)return;const p=probeFrame();if(!p){scheduleLive(700);return}const motion=probeDelta(p,lastProbe);lastProbe=p;if(motion<4.2)stableHits++;else stableHits=0;if(stableHits<2){$('#status').textContent=lang==='en'?'Waiting for a stable projected frame…':'Menunggu frame proyektor yang stabil…';scheduleLive(650);return}const changed=probeDelta(p,lastSentProbe);if(lastSentProbe&&changed<2.1){$('#status').textContent=lang==='en'?'Stable frame unchanged. Waiting for the next slide…':'Frame stabil belum berubah. Menunggu slide berikutnya…';scheduleLive(850);return}const sent=await send(true);if(sent){lastSentProbe=p;stableHits=0;scheduleLive(1800)}else{stableHits=Math.max(stableHits,2);scheduleLive(900)}}
function scheduleLive(ms=800){if(!liveRunning)return;clearTimeout(liveTimer);liveTimer=setTimeout(liveTick,ms)}
function toggleLive(){if(!stream){$('#status').textContent=tr().cameraFail;return}liveRunning=!liveRunning;$('#liveBtn').textContent=liveRunning?tr().liveStop:tr().liveStart;if(liveRunning){lastProbe=null;lastSentProbe=null;stableHits=0;$('#status').textContent=tr().liveActive;scheduleLive(250)}else{clearTimeout(liveTimer);liveTimer=null;$('#status').textContent=tr().ready}}
$('#joinBtn').onclick=pairCode;$('#joinCode').addEventListener('keydown',e=>{if(e.key==='Enter')pairCode()});$('#cameraBtn').onclick=openCamera;$('#sendBtn').onclick=()=>send(false);$('#liveBtn').onclick=toggleLive;$('#photoInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>showDataUrl(rd.result);rd.readAsDataURL(f)};$('#langBtn').onclick=()=>{lang=lang==='en'?'id':'en';try{localStorage.setItem('backrow-lang',lang)}catch{}renderLang()};
window.addEventListener('beforeunload',()=>{liveRunning=false;clearTimeout(liveTimer);if(stream)stream.getTracks().forEach(t=>t.stop())});init();
