const $=s=>document.querySelector(s);let timers={manual:null,backrow:null},elapsed={manual:0,backrow:0},deckId=null,deckCount=0,stream=null,frames=[],collecting=false;
const T={
 en:{tag:'FIELD VALIDATION CONSOLE',eyebrow:'LOCKED PHYSICAL EVALUATION',title:'Measure the baselines. Do not estimate them.',intro:'This console only records real timings and real deck matches. It does not generate a success score.',workflowKicker:'MANUAL vs BACKROW',workflowTitle:'Workflow timing',workflowHelp:'Use the same 15+ slide rehearsal and the same planted/known critical failures for both methods.',slides:'Slides',known:'Known critical failures',manualFound:'Manual failures found',backrowFound:'BACKROW failures found',manualStart:'Start manual',backrowStart:'Start BACKROW',stop:'Stop',noTiming:'No timing recorded.',exportWorkflow:'Export workflow JSON',projectorKicker:'REAL PROJECTOR',retrievalTitle:'Stable-frame deck retrieval',retrievalHelp:'Upload the exact deck, project one slide, tell the console the true page number, then collect camera frames. Rejections are kept as failures instead of being deleted.',loadPdf:'Load PDF',noDeck:'No deck loaded.',expected:'Expected slide',openCamera:'Open audience camera',cameraGuide:'Keep the full projector inside frame. Wait until transitions stop.',captureOne:'Capture 1 stable frame',captureFive:'Collect 5 frames',closeCamera:'Close camera',minimumFrames:'/ 50 minimum stable frames',noFrames:'No frames recorded.',multiFrames:'Use multiple real slides/positions; do not collect 50 copies of one easy frame.',exportDeck:'Export deck-match JSON',handoffKicker:'HANDOFF',handoffTitle:'Locked evaluator inputs',handoffHelp:'Pair these two exports with the blinded field-study exports. The evaluator refuses incomplete evidence.',recordBoth:'Record both methods before export.',invalidWorkflow:'Use ≥15 slides and valid critical-failure counts.',indexing:'Indexing deck…',slidesIndexed:n=>`${n} slides indexed · session ready`,pdfFailed:'PDF failed',cameraUnavailable:e=>`Camera unavailable: ${e}`,frameNotReady:'Camera frame not ready.',loadFirst:'Load deck first.',outsideDeck:'Expected slide is outside this deck.',noMatch:'No match',acc:(a)=>`${(a*100).toFixed(1)}% accepted-correct / all stable frames`,expectedN:n=>`expected ${n}`,rejected:'REJECTED',matched:n=>`matched ${n}`,collecting5:'Collecting 5 stable frames…',done5:'5-frame collection complete.'},
 id:{tag:'KONSOL VALIDASI LAPANGAN',eyebrow:'EVALUASI FISIK TERKUNCI',title:'Ukur baseline-nya. Jangan menebak.',intro:'Konsol ini hanya merekam waktu nyata dan kecocokan deck nyata. Konsol tidak membuat skor keberhasilan.',workflowKicker:'MANUAL vs BACKROW',workflowTitle:'Waktu workflow',workflowHelp:'Gunakan rehearsal 15+ slide yang sama dan kegagalan kritis yang sama/ditanam untuk kedua metode.',slides:'Jumlah slide',known:'Total kegagalan kritis yang diketahui',manualFound:'Kegagalan ditemukan manual',backrowFound:'Kegagalan ditemukan BACKROW',manualStart:'Mulai manual',backrowStart:'Mulai BACKROW',stop:'Stop',noTiming:'Belum ada waktu yang direkam.',exportWorkflow:'Ekspor JSON workflow',projectorKicker:'PROYEKTOR NYATA',retrievalTitle:'Pencocokan deck dari frame stabil',retrievalHelp:'Unggah deck yang tepat, proyeksikan satu slide, beri tahu nomor halaman yang benar, lalu kumpulkan frame kamera. Frame yang ditolak tetap dihitung sebagai kegagalan, bukan dihapus.',loadPdf:'Muat PDF',noDeck:'Belum ada deck.',expected:'Slide yang benar',openCamera:'Buka kamera penonton',cameraGuide:'Pastikan seluruh proyektor masuk frame. Tunggu sampai transisi berhenti.',captureOne:'Ambil 1 frame stabil',captureFive:'Kumpulkan 5 frame',closeCamera:'Tutup kamera',minimumFrames:'/ minimal 50 frame stabil',noFrames:'Belum ada frame.',multiFrames:'Gunakan beberapa slide/posisi nyata; jangan mengumpulkan 50 salinan dari satu frame mudah.',exportDeck:'Ekspor JSON deck-match',handoffKicker:'HANDOFF',handoffTitle:'Input evaluator terkunci',handoffHelp:'Pasangkan dua ekspor ini dengan hasil blind field-study. Evaluator menolak bukti yang tidak lengkap.',recordBoth:'Rekam kedua metode sebelum ekspor.',invalidWorkflow:'Gunakan ≥15 slide dan jumlah kegagalan kritis yang valid.',indexing:'Mengindeks deck…',slidesIndexed:n=>`${n} slide terindeks · sesi siap`,pdfFailed:'PDF gagal diproses',cameraUnavailable:e=>`Kamera tidak tersedia: ${e}`,frameNotReady:'Frame kamera belum siap.',loadFirst:'Muat deck terlebih dahulu.',outsideDeck:'Nomor slide yang benar berada di luar deck ini.',noMatch:'Tidak ada kecocokan',acc:(a)=>`${(a*100).toFixed(1)}% benar-terima / seluruh frame stabil`,expectedN:n=>`seharusnya ${n}`,rejected:'DITOLAK',matched:n=>`cocok ${n}`,collecting5:'Mengumpulkan 5 frame stabil…',done5:'Pengumpulan 5 frame selesai.'}
};
let lang=BACKROW_LOCALE.get();function tr(k,...a){const v=T[lang][k];return typeof v==='function'?v(...a):v||k}function translate(){lang=BACKROW_LOCALE.get();document.querySelectorAll('[data-i18n]').forEach(el=>{const v=tr(el.dataset.i18n);if(v)el.textContent=v});$('#langBtn').textContent=lang==='en'?'ID':'EN';document.title=lang==='en'?'BACKROW — Field Validation Console':'BACKROW — Konsol Validasi Lapangan';updateWorkflow();renderFrames()}window.addEventListener('backrow:lang',translate);$('#langBtn').onclick=()=>BACKROW_LOCALE.toggle();
function format(ms){const t=Math.max(0,ms)/1000,m=Math.floor(t/60),s=t-m*60;return `${String(m).padStart(2,'0')}:${s.toFixed(1).padStart(4,'0')}`}
function startTimer(k){if(timers[k])return;const started=performance.now()-elapsed[k];timers[k]={started,raf:0};const tick=()=>{if(!timers[k])return;elapsed[k]=performance.now()-started;$(`#${k}Clock`).textContent=format(elapsed[k]);timers[k].raf=requestAnimationFrame(tick)};tick();$(`#${k}Start`).disabled=true;$(`#${k}Stop`).disabled=false}
function stopTimer(k){const t=timers[k];if(!t)return;cancelAnimationFrame(t.raf);timers[k]=null;$(`#${k}Start`).disabled=false;$(`#${k}Stop`).disabled=true;updateWorkflow()}
function updateWorkflow(){const ok=elapsed.manual>0&&elapsed.backrow>0;$('#exportWorkflow').disabled=!ok;$('#workflowState').textContent=ok?`Manual ${format(elapsed.manual)} · BACKROW ${format(elapsed.backrow)}`:tr('recordBoth')}
function download(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('#manualStart').onclick=()=>startTimer('manual');$('#manualStop').onclick=()=>stopTimer('manual');$('#backrowStart').onclick=()=>startTimer('backrow');$('#backrowStop').onclick=()=>stopTimer('backrow');
$('#exportWorkflow').onclick=()=>{const slides=Number($('#wfSlides').value),total=Number($('#wfCriticalTotal').value),mf=Number($('#manualFound').value),bf=Number($('#backrowFound').value);if(slides<15||total<1||mf<0||bf<0||mf>total||bf>total)return alert(tr('invalidWorkflow'));download({schema:'backrow-workflow-timing-v1',measured_at:new Date().toISOString(),slides,manual_seconds:+(elapsed.manual/1000).toFixed(3),backrow_seconds:+(elapsed.backrow/1000).toFixed(3),manual_critical_recall:+(mf/total).toFixed(6),backrow_critical_recall:+(bf/total).toFixed(6),critical_failures_total:total,manual_critical_found:mf,backrow_critical_found:bf,notes:'Measured with the same frozen rehearsal deck and known critical failures. Do not edit after locked evaluation.'},'BACKROW_WORKFLOW.json')}
function fileDataURL(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
$('#deckPdf').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;$('#deckState').textContent=tr('indexing');try{const pdf=await fileDataURL(f),r=await fetch('/api/render_pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pdf})}),j=await r.json();if(!j.ok)throw new Error(j.error||tr('pdfFailed'));deckId=j.deckId;deckCount=j.count;$('#expectedSlide').max=String(deckCount);$('#openValidationCamera').disabled=false;$('#deckState').textContent=tr('slidesIndexed',deckCount);frames=[];renderFrames()}catch(err){deckId=null;$('#openValidationCamera').disabled=true;$('#deckState').textContent=err.message}}
$('#openValidationCamera').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});$('#validationVideo').srcObject=stream;$('#validationCameraWrap').classList.remove('hidden')}catch(e){alert(tr('cameraUnavailable',e.message))}};
function closeCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('#validationVideo').srcObject=null;$('#validationCameraWrap').classList.add('hidden')}$('#closeValidationCamera').onclick=closeCamera;
function captureDataURL(){const v=$('#validationVideo'),c=$('#validationCanvas');if(!v.videoWidth)throw new Error(tr('frameNotReady'));const max=1600,s=Math.min(1,max/v.videoWidth);c.width=Math.round(v.videoWidth*s);c.height=Math.round(v.videoHeight*s);c.getContext('2d').drawImage(v,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.88)}
async function captureStable(){if(!deckId)throw new Error(tr('loadFirst'));const expected=Number($('#expectedSlide').value);if(!(expected>=1&&expected<=deckCount))throw new Error(tr('outsideDeck'));const row={frame_id:`F${String(frames.length+1).padStart(3,'0')}`,stable:true,expected_slide:expected,matched_slide:null,rejected:false,deck_match_ms:null,captured_at:new Date().toISOString()};try{const view=captureDataURL(),r=await fetch('/api/deck_match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deckId,view})}),j=await r.json();if(!j.ok)throw new Error(j.error||tr('noMatch'));row.matched_slide=j.matched_slide_index+1;row.deck_match_ms=j.deck_match_ms;row.inliers=j.alignment?.inliers??null;row.inlier_ratio=j.alignment?.inlier_ratio??null}catch(e){row.rejected=true;row.error=String(e.message||e)}frames.push(row);renderFrames();return row}
function renderFrames(){const total=frames.length,correct=frames.filter(x=>x.matched_slide===x.expected_slide).length,acc=total?correct/total:null;$('#frameCount').textContent=String(total);$('#matchAccuracy').textContent=acc===null?'—':tr('acc',acc);$('#exportDeck').disabled=!total;$('#frameLedger').innerHTML=total?frames.slice(-12).reverse().map(x=>`<div class="frameRow"><span>${x.frame_id}</span><b>${tr('expectedN',x.expected_slide)}</b><b>${x.rejected?tr('rejected'):tr('matched',x.matched_slide)}</b><small>${x.deck_match_ms==null?'—':`${x.deck_match_ms} ms`}</small></div>`).join(''):`<span>${tr('noFrames')}</span>`}
$('#captureOne').onclick=async()=>{try{await captureStable()}catch(e){alert(e.message)}};$('#captureFive').onclick=async()=>{if(collecting)return;collecting=true;$('#captureFive').disabled=true;$('#captureFive').textContent=tr('collecting5');try{for(let i=0;i<5;i++){await captureStable();await new Promise(r=>setTimeout(r,500))}}catch(e){alert(e.message)}finally{collecting=false;$('#captureFive').disabled=false;$('#captureFive').textContent=tr('captureFive')}};
$('#exportDeck').onclick=()=>{if(!frames.length)return;const correct=frames.filter(x=>x.matched_slide===x.expected_slide).length;download({schema:'backrow-real-deck-match-v1',measured_at:new Date().toISOString(),stable_frames_total:frames.length,stable_frames_correct:correct,stable_frame_accuracy:+(correct/frames.length).toFixed(6),frames,notes:'All collected stable frames retained, including rejections.'},'BACKROW_DECK_MATCH.json')};
translate();
