#!/usr/bin/env python3
from __future__ import annotations
import base64,json,os,re
from playwright.sync_api import sync_playwright
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'));OUT=os.path.join(ROOT,'preview');os.makedirs(OUT,exist_ok=True)
img='data:image/png;base64,'+base64.b64encode(open(os.path.join(ROOT,'assets','slide_2_source.png'),'rb').read()).decode()
study={'schema':'backrow-field-study-v2','study_id':'TESTFIELD1234','title':'BACKROW locked projector study','deck_name':'demo deck','room':{'farthest_seat_m':8.4,'image_height_m':1.8},'slides':{'1':img},'items':[{'id':'item001','ordinal':1,'slide':1,'source_size':{'width':1600,'height':900},'source_text':'Launch only if error rate stays below 2.5%.','box':[112,679,410,22],'camera_text':'Launch only if error rate stays below 25%','camera_confidence':92.2,'status':'at_risk','physical_baseline':{'status':'below'}}],'responses':[],'exposure_seconds':3.0,'presentation_order':['item001'],'presentation_events':[]}
public={'schema':study['schema'],'study_id':study['study_id'],'title':study['title'],'deck_name':study['deck_name'],'item_count':1,'exposure_seconds':3.0,'completed_item_ids':[],'items':[{'id':'item001','sequence':1,'slide':1}],'instructions':'Look only at the real projector/display.'}
css=open(os.path.join(ROOT,'styles.css'),encoding='utf-8').read();locale=open(os.path.join(ROOT,'locale.js'),encoding='utf-8').read()
def inline(name,jsname,stub):
    h=open(os.path.join(ROOT,name),encoding='utf-8').read();js=open(os.path.join(ROOT,jsname),encoding='utf-8').read();h=re.sub(r'<link rel="stylesheet" href="styles.css"\s*/?>',f'<style>{css}</style>',h);h=h.replace('<script src="locale.js"></script>',f'<script>{locale}</script>');return h.replace(f'<script src="{jsname}"></script>',f'<script>{stub}</script><script>{js}</script>')
admin_stub=f"window.URLSearchParams=class{{constructor(){{}}get(k){{return k==='study'?'TESTFIELD1234':(k==='token'?'ADMINTOKEN1234567890':null)}}}};window.fetch=async(url,opt)=>({{ok:true,json:async()=>url.includes('/api/study/present')?({{ok:true,recorded:'ok'}}):({{ok:true,study:{json.dumps(study)}}})}});"
reader_stub=f"window.__pubPoll=0;window.URLSearchParams=class{{constructor(){{}}get(k){{return k==='study'?'TESTFIELD1234':null}}}};window.fetch=async(url,opt)=>({{ok:true,json:async()=>{{if(url.includes('/public')){{window.__pubPoll++;const s={json.dumps(public)};if(window.__pubPoll>1)s.completed_item_ids=['item001'];return {{ok:true,study:s}}}}return {{ok:true,saved:1}}}}}});"
admin_html=inline('study_admin.html','study_admin.js',admin_stub);reader_html=inline('study.html','study.js',reader_stub)
with sync_playwright() as pw:
    b=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox'])
    admin=b.new_page(viewport={'width':1440,'height':1000});admin.set_content(admin_html,wait_until='load');admin.wait_for_selector('#projectionStage:not(.hidden)');assert 'Launch only' in admin.locator('#truthGrid').text_content();assert admin.locator('#runExposure').is_visible();assert '3 s' in admin.locator('#adminMeta').inner_text();assert admin.locator('#targetCue').is_visible();admin.click('#runExposure');admin.wait_for_timeout(1350);assert admin.locator('#projectedSlide').is_visible();assert admin.locator('#targetBox').is_hidden();admin.locator('.studyTruth details').evaluate('(e)=>e.open=true');admin.screenshot(path=os.path.join(OUT,'BACKROW_FIELD_STUDY_ADMIN.png'),full_page=True)
    reader=b.new_page(viewport={'width':390,'height':844});reader.set_content(reader_html,wait_until='load');reader.wait_for_selector('#readerForm:not(.hidden)');body=reader.locator('body').inner_text();assert 'Launch only' not in body and '25%' not in body;assert reader.locator('#submitStudy').is_disabled();reader.wait_for_function("!document.querySelector('[data-item]').disabled",timeout=4000);assert reader.locator('#submitStudy').is_enabled();reader.screenshot(path=os.path.join(OUT,'BACKROW_FIELD_STUDY_READER.png'),full_page=True);reader.fill('#participantCode','R01');reader.fill('[data-item]','Launch only if error rate stays below 2.5%.');reader.click('button[type=submit]');reader.wait_for_selector('#studyDone:not(.hidden)');b.close()
out={'ok':True,'participant_truth_hidden':True,'admin_truth_available':True,'browser_response_flow':True,'pre_exposure_cue_without_live_overlay':True,'reader_locked_until_exposure':True,'screenshots':['BACKROW_FIELD_STUDY_ADMIN.png','BACKROW_FIELD_STUDY_READER.png']};print(json.dumps(out,indent=2));json.dump(out,open(os.path.join(ROOT,'docs','browser_field_study_verification.json'),'w'),indent=2)
